### ISSUE TITLE
when speaker detection is set to 'auto' the worker crashes

### ISSUE THREAD

**Issue by anuejn** [bugbakery/transcribee#329]
```
worker   | Traceback (most recent call last):
worker   |   File "/Users/anuejn/Developer/transcribee/worker/transcribee_worker/worker.py", line 337, in run_task
worker   |     task_result = await self.perform_task(task)
worker   |   File "/Users/anuejn/Developer/transcribee/worker/transcribee_worker/worker.py", line 151, in perform_task
worker   |     await self.identify_speakers(task, progress_callback)
worker   |   File "/Users/anuejn/Developer/transcribee/worker/transcribee_worker/worker.py", line 188, in identify_speakers
worker   |     task.task_parameters.number_of_speakers != 0
worker   | AttributeError: 'dict' object has no attribute 'number_of_speakers'
```

**Comment by phlmn** [comment]
This is fixed, right?

**Comment by phlmn** [comment]
seems to be fixed
