### ISSUE TITLE
Alignment step failed in dev environment

### ISSUE THREAD

**Issue by moeffju** [bugbakery/transcribee#352]
On commit `ebb0e97d232891a8b89c5b7ee6e20568d44ee99a` running in dev mode in a debian+nix dev container, the alignment step failed with this traceback:

```
backend  | INFO:     127.0.0.1:46808 - "POST /api/v1/tasks/63514bcc-498c-4da6-bfe5-0d3f2e8c72d8/keepalive/ HTTP/1.1" 200 OK
backend  | INFO:     connection closed
worker   | WARNING:root:Worker failed with exception
worker   | Traceback (most recent call last):
worker   |   File "/workspaces/transcribee/worker/transcribee_worker/worker.py", line 354, in run_task
worker   |     task_result = await self.perform_task(task)
worker   |   File "/workspaces/transcribee/worker/transcribee_worker/worker.py", line 165, in perform_task
worker   |     await self.align(task, progress_callback)
worker   |   File "/workspaces/transcribee/worker/transcribee_worker/worker.py", line 233, in align
worker   |     async for i, al_para in aenumerate(aligned_para_iter):
worker   |   File "/workspaces/transcribee/worker/transcribee_worker/util.py", line 84, in aenumerate
worker   |     async for elem in iterable:
worker   |   File "/workspaces/transcribee/worker/transcribee_worker/util.py", line 64, in async_task
worker   |     value = fut.result()
worker   |   File "/nix/store/iw1vmh509hcbby8dbpsaanbri4zsq7dj-python3-3.10.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
worker   |     result = self.fn(*self.args, **self.kwargs)
worker   |   File "/workspaces/transcribee/worker/transcribee_worker/util.py", line 50, in _work_task
worker   |     work_function(SubmissionQueue(loop, result_queue), *args, **kwargs)
worker   |   File "/workspaces/transcribee/worker/transcribee_worker/torchaudio_align.py", line 260, in work
worker   |     (start, last_end), (end, next_start) = atom_index_to_timing_index[i]
worker   | TypeError: cannot unpack non-iterable NoneType object
backend  | INFO:     127.0.0.1:46818 - "POST /api/v1/tasks/63514bcc-498c-4da6-bfe5-0d3f2e8c72d8/mark_failed/ HTTP/1.1" 200 OK
```

Align encoding info:

```
worker   | Input #0, mp3, from '/tmp/user/1000/tmpnjgkb5iu/doc_audio.mp3':
worker   |   Metadata:
worker   |     encoder         : Lavf58.76.100
worker   |   Duration: 00:46:30.50, start: 0.023021, bitrate: 128 kb/s
worker   |   Stream #0:0: Audio: mp3, 48000 Hz, mono, fltp, 128 kb/s
worker   | Stream mapping:
worker   |   Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_f32le (native))
worker   | Press [q] to stop, [?] for help
worker   | Output #0, f32le, to 'pipe:':
worker   |   Metadata:
worker   |     encoder         : Lavf58.76.100
worker   |   Stream #0:0: Audio: pcm_f32le, 16000 Hz, mono, flt, 512 kb/s
worker   |     Metadata:
worker   |       encoder         : Lavc58.134.100 pcm_f32le
```

Task:

```
worker   | INFO:root:Running task: task=AlignTask(id='63514bcc-498c-4da6-bfe5-0d3f2e8c72d8', document=Document(id='4bf41663-7246-4982-a1a7-0757c48e1c2a', name="Jens Spahn's Credit Score", created_at='2023-09-17T19:27:11.734226', changed_at='2023-09-17T19:27:11.734226', media_files=[DocumentMedia(url='http://localhost:8000/media/cdab5816-04be-4002-ad89-dd139864c900?X-Transcribee-Signature=eyJmaWxlIjogImNkYWI1ODE2LTA0YmUtNDAwMi1hZDg5LWRkMTM5ODY0YzkwMCIsICJ0aW1lc3RhbXAiOiAxNjk0OTgwNTIxfQ%3AxYkI41EZDKgO4KL-4URXMBb1V5o', content_type='audio/mpeg', tags=['original']), DocumentMedia(url='http://localhost:8000/media/b57b59a4-1134-4c49-8755-2344032e3ec9?X-Transcribee-Signature=eyJmaWxlIjogImI1N2I1OWE0LTExMzQtNGM0OS04NzU1LTIzNDQwMzJlM2VjOSIsICJ0aW1lc3RhbXAiOiAxNjk0OTgwNTIxfQ%3AAyP9Um4RC5WfmiRK8PYC80CDbWM', content_type='audio/mpeg', tags=['profile:mp3', 'format:mp3', 'audio_bitrate:128k', 'ac:1']), DocumentMedia(url='http://localhost:8000/media/d16e0624-d09f-4378-ad1b-c132cc8d511f?X-Transcribee-Signature=eyJmaWxlIjogImQxNmUwNjI0LWQwOWYtNDM3OC1hZDFiLWMxMzJjYzhkNTExZiIsICJ0aW1lc3RhbXAiOiAxNjk0OTgwNTIxfQ%3AhSHIHlWjMAc9VXwbnv-iOp13km8', content_type='video/mp4', tags=['profile:m4a', 'format:mp4', 'audio_bitrate:128k', 'ac:1'])]), task_type=<TaskType.ALIGN: 'ALIGN'>, task_parameters={})
```

**Comment by phlmn** [comment]
This comes from this line unpacking tuples which can be `None`

https://github.com/bugbakery/transcribee/blob/74d1c4d3a2c0daea41197c5201072bc27dd6e49a/worker/transcribee_worker/torchaudio_align.py#L260

as can be seen here:

https://github.com/bugbakery/transcribee/blob/74d1c4d3a2c0daea41197c5201072bc27dd6e49a/worker/transcribee_worker/torchaudio_align.py#L189-L210

I'm not sure what should happen when tuples are `None` @rroohhh ? Also I think we should add types here and switch to more consistent variable names.
